### ISSUE TITLE
Alarm Klock crashes when changing what to display on lockscreen

### ISSUE THREAD

**Issue by Domochevsky** [kraigs-android/kraigsandroid#107]
Hey, the app crashes as mentioned in the title, but only there. The device is a vanilla Galaxy S6 edge with stock rom.
What other information do you require?

**Comment by kraigs-android** [comment]
Which version of android and this app are you using?  This feature was removed from android in Lollipop when they added lock screen notifications.  It has been removed from this application as a result in newer versions.  I'm afraid your only options are to upgrade to the current version of the app or to simply not try to use the feature in whatever version you are running.

**Comment by Domochevsky** [comment]
Lesse... 
The Android version is 6.0.1.
Alarm Klock's version is 1.10, which was obtained from the F-Droid store.
If there's a newer version, where would I get that from?

**Comment by kraigs-android** [comment]
The latest version is 2.2 and is in the Google Play store:
https://play.google.com/store/apps/details?id=com.angrydoughnuts.android.alarmclock

You can also get all of the APK versions in the downloads repository on github:
https://github.com/kraigs-android/kraigsandroid-downloads
