### ISSUE TITLE
Daylight Savings Time?

### ISSUE THREAD

**Issue by aimaynard523** [kraigs-android/kraigsandroid#108]
Yesterday when i used it, every alarm sounded 2 times. Once an hour before then at the time it was set to. For example, it would alarm at 3:30 am, then again (without snooze) at 4:30 am. Same for my afternoon alarm; once at 3:22 pm then again at 4:22 pm.

**Comment by kraigs-android** [comment]
Thanks, I've already fixed this issue, but since it only happens on the day of the time change, I'm going to hold off releasing it a bit longer in case anything else comes up.
https://github.com/kraigs-android/kraigsandroid/commit/dfa3dd862e7d4f664a374638d073b5706ef43bf3

**Comment by aimaynard523** [comment]
Thanks for getting back on this! I figured that is what happened and don't
blame you for it lol
