### ISSUE TITLE
little correction for German string

### ISSUE THREAD

**Issue by paulle** [kraigs-android/kraigsandroid#113]
I corrected some minor things in German translation. Don't know how to it in github. So I attach the original translation and

[alarm klock de-corr.txt](https://github.com/kraigs-android/kraigsandroid/files/714104/alarm.klock.de-corr.txt)
[alarm klock de.txt](https://github.com/kraigs-android/kraigsandroid/files/714103/alarm.klock.de.txt)

 the corrected one.

**Comment by kraigs-android** [comment]
Thank you!  I've just committed your change: 47b5f145fa3d2021a78185dbd6cd0860cdc5e94c

Unfortunately I've just released a new version, so this will need to wait a couple months before the next release.  I've uploaded a test version if you'd like to install it and try it out.
https://github.com/kraigs-android/kraigsandroid-downloads/blob/master/Alarm%20Klock-2.3-german-fix.apk
