### ISSUE TITLE
Large snooze button mode 

### ISSUE THREAD

**Issue by neomodern** [kraigs-android/kraigsandroid#115]
Setting to choose a near full-screen snooze button mode which requires only a tap like this:

![Alarm Clock Xtreme](https://lh3.googleusercontent.com/esfIaaAHy3_2jnj7tVZqAMuWKj7rqI7s0F3NDfqTN5hkxdYhWsOwu4STiKaNL3YM5A=h310)

Much easier than the small swipe bar at the bottom (especially when tired).

**Comment by kraigs-android** [comment]
I'm trying to keep the number of customization options to a minimum.

**Comment by Jai-GAY** [comment]
you wouldn't want to miss your important flight just because you wanted to hold the phone to snooze for few minuets and accidentally dismissed it (happen to me once). button press dismiss in alarm application is really a poor consideration in real using cases.
