### ISSUE TITLE
Spinning wheel-type UI for changing alarm time instead of arrows

### ISSUE THREAD

**Issue by neomodern** [kraigs-android/kraigsandroid#116]
Similar to this:
![spinning wheel](http://static.cubiq.org/uploads/2009/03/Spinning-Wheel-slot-machine-alike.jpeg)

Faster and more intuitive than the current arrow method.

**Comment by kraigs-android** [comment]
For fast input, I'd suggest using the key pad input.  This screenshot is clearly from an iPhone, which I am not interested in copying.

**Comment by Jai-GAY** [comment]
actually a faster and intuitive input method is this (2 clicks to get the job done)
[android-betterpickers](https://github.com/code-troopers/android-betterpickers)
