### ISSUE TITLE
[Question] Why does it require Android 6.x since 2.2? (F-Droid)

### ISSUE THREAD

**Issue by OffifialMITX** [kraigs-android/kraigsandroid#117]

**Comment by kraigs-android** [comment]
The maintenance burden of supporting older versions was too high.  When I re-wrote the app for version 2.0, I started fresh with the latest version of android (which was Marshmallow at the time).  You can still use the pre-2.0 versions for older android versions.

**Comment by alanthehat** [comment]
This question is asked again in #135
