### ISSUE TITLE
Not able  to use a music file for Alarm

### ISSUE THREAD

**Issue by livier** [kraigs-android/kraigsandroid#118]
I, 
When I want to choose a file as ring (Choix de sonnerie, in French) I have a little Window with"Interne | Artistes | Album | Chanson" Tabs shown, but nothing in none of them in any way.
I'm a bit sad, because I used it a while ago. maybe some updates and some month not using the app, but I wanted to use it again with my favorit song to wake up.

Alarm Clock 1.10 Android 4.0.4 Samsung GT-S7560M

**Comment by kraigs-android** [comment]
You need to allow the application to access your phone's storage device in order to play music from your phone.  It should have prompted you for permission when you installed it.  If you dismissed it, you can re-enable it in Settings->Apps->Alarm Klock->Permissions.

**Comment by livier** [comment]
Just see your answer whwn you close ticket / excuses
Problem of permission, yes probably. Whith my old device, Only Alarm Clock 1.10 is proposed (1.9 not available for download on F-Droid) and permission is not required for accessing files on the device, so it does not find them ! .
Settings->Apps->Alarm Klock does not have a way to open permission (Android 4.0.4)
Not a big problem in my life, but ...
