### ISSUE TITLE
vibration continues after dismiss/snooze

### ISSUE THREAD

**Issue by haxwithaxe** [kraigs-android/kraigsandroid#119]
# Observed behavior
1. alarm goes off
2. dismiss or snooze alarm
3. vibration continues. usually less than a minute. once it didn't stop until i rebooted my phone.

this seems to happen more frequently when my phone is locked but that may be my imagination.

# Expected behavior
1. alarm goes off
2. dismiss or snooze alarm and vibration stops.

# Environment
phone: nexus 6
os: stock 7.01
lock screen: pin
version: 2.3 from play store.

**Comment by kraigs-android** [comment]
I haven't been able to reproduce this.  The vibration is controlled by the notification that pops up when an alarm goes off.  Perhaps if you had changed the system-level notification settings it may interfere with this?  Settings->Apps->Alarm Klock->Notifications.  Maybe one of these is messing with it?  What are these options set to?

**Comment by haxwithaxe** [comment]
all unchecked, default locksceen visibility.

**Comment by kraigs-android** [comment]
That's pretty weird then.  The vibration is really just an attribute of the notification that shows up in the notification bar when an alarm is going off.  The android libraries/OS take care of all of the actual vibration control.  The app really just says 'vibrate when this notification is visible, stop when it's not'.  So I guess it would be interesting to know if you can still see the notification in the notification bar when this is happening.  If it's till there, it means the dismiss is not removing the notification for some reason.  If it's not there, it sounds like it might be triggering a bug in the android notification system somewhere...

**Comment by haxwithaxe** [comment]
GOOD NEWS! the same thing just happened with hangouts.
