### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by FTno** [kraigs-android/kraigsandroid#123]
[strings.zip](https://github.com/kraigs-android/kraigsandroid/files/1411278/strings.zip)
Hello, and thank you for the Alarm Klock app.
I liked it so much that I decided to translate the app into my language.
Here is a norwegian language file for Alarm Klock

**Comment by kraigs-android** [comment]
merged

**Comment by FTno** [comment]
I don't know the language code used then you merged the norwegian language file, but it must be 'nb' and not 'no'.
Something I found out after recently translating another app, as can be seen in this thread: https://github.com/SimpleMobileTools/Simple-Calendar/issues/281
