### ISSUE TITLE
Can't see alarm on Android 10

### ISSUE THREAD

**Issue by Fohroer** [kraigs-android/kraigsandroid#142]
Hello!

Phone: Xiaomi Mi A3
Firmware: Paranoid Android
When alarm rings I can't see it without unblocking the screen. Please fix it.

**Comment by Fohroer** [comment]
Please close this. I didn't know that there is a new version on Google Play. I have used old one from F-droid.
If you can update it on F-droid, please do it.

**Comment by kraigs-android** [comment]
Sorry, I don't have access to the f-droid version.  I didn't even know it was on there :)  You'll need to contact whoever maintains that an ask them to pull a new version.
