### ISSUE TITLE
Snooze doesn't work - just resets to next alarm

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kraigs-android/kraigsandroid#86]
```
What steps will reproduce the problem?
1.set alarm
2.wait for alarm to go off
3.press snooze

What is the expected output? What do you see instead?

Expected alarm to snooze 5 mins. Instead it reset to the next alarm (24hrs)
What version of the product are you using? On what operating system?

Version 1.7 on Samsung Galaxy S3
Please provide any additional information below.

```

Original issue reported on code.google.com by `sallyham...@googlemail.com` on 20 May 2013 at 7:42

**Comment by ftobin** [comment]
I'm so looking forward to trying out the fixed version!  This is still my favorite alarm clock app by far.

**Comment by kraigs-android** [comment]
It should be available in the play store now.
https://play.google.com/store/apps/details?id=com.angrydoughnuts.android.alarmclock
